name: jd_baiTiao_yangtingxiao

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,16 * * *"
  watch:
    types: [started]
  repository_dispatch:
    types: jd_baiTiao_yangtingxiao

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout github_lxk0301_jd_scripts
        uses: actions/checkout@v2
        with:
          repository: fq3/github_lxk0301_jd_scripts
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: npm install
      - name: "Run jd_baiTiao_yangtingxiao"
        run: |
          wget -q -O jd_baiTiao_yangtingxiao.js https://github.com/fq3/github_yangtingxiao_QuantumultX/raw/master/scripts/jd/jd_baiTiao.js
          node jd_baiTiao_yangtingxiao.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          SYNCURL: https://github.com/fq3/github_yangtingxiao_QuantumultX/raw/master/scripts/jd/jd_baiTiao.js
