name: jd_dreamFactory_hundun

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
  watch:
    types: [started]
  repository_dispatch:
    types: jd_dreamFactory_hundun

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout github_lxk0301_jd_scripts
        uses: actions/checkout@v2
        with:
          repository: fq3/github_lxk0301_jd_scripts
          ref: master
          path: scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          cd scripts
          npm install
      - name: "Run jd_dreamFactory_hundun"
        run: |
          cd scripts
          wget -q -O jd_dreamFactory_hundun.js https://github.com/fq3/github_whyour_hundun/raw/master/quanx/jx_factory.js
          node jd_dreamFactory_hundun.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
          SYNCURL: https://github.com/fq3/github_whyour_hundun/raw/master/quanx/jx_factory.js